export default [
  // Content Team
  {
    Column2: "1/3/2024 23:55:14",
    name: "Kanishk Krishnan",
    position: "Head",
    team: "Content",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436910/smvbrwcwmjnhpdnitwj2.jpg",
    linkedin_url: "https://www.linkedin.com/in/kanishk-krishnan-22b325228/",
    insta_url: "https://www.instagram.com/kanishk.krishnan/",
  },
  {
    Column2: "1/4/2024 17:57:57",
    name: "Spriha Ghosh",
    position: "Co-Head",
    team: "Content team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436896/ujnmyvnjsdrgxexodkr9.jpg",
    linkedin_url: "https://www.linkedin.com/in/spriha-ghosh-0136121b4",
    insta_url: "https://www.instagram.com/spriiihaaa?igsh=MXUwZ21iaXk0bmtrZg==",
  },
  
  // Design Team
  {
    Column2: "1/4/2024 17:36:41",
    name: "Amit Singh Yadav ",
    position: "Co-Head",
    team: "Design Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436946/v4abasmvqbs3kx3kdxd4.jpg",
    linkedin_url: "https://www.linkedin.com/in/amit-singh-yadav-a02a08218?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    insta_url: "https://www.instagram.com/vkamit_?igsh=MWhid2NqejdrdzA2dA==",
  },
  {
    Column2: "1/4/2024 22:32:02",
    name: "Jeet Rathod ",
    position: "Head",
    team: "Design Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436897/tqpkck8knb1hrtuqijlk.jpg",
    linkedin_url: "https://www.linkedin.com/in/jeet-rathod-7994b3228",
    insta_url: "https://www.instagram.com/jeet.rathod_?utm_source=qr&igsh=ZGNsMDl2NnhmcnFj",
  },
  {
    Column2: "1/4/2024 22:43:30",
    name: "Kantale Sujeeth",
    position: "Co-Head",
    team: "Design Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436949/alhj35lgrulql00xkefv.jpg",
    linkedin_url: "https://www.linkedin.com/in/kantale-sujeeth-3b6935235/",
    insta_url: "https://instagram.com/https://www.instagram.com/sujeeth_kantale/",
  },
  
  // Documentation Team
  {
    Column2: "1/4/2024 22:28:29",
    name: "Megh Gupta",
    position: "Head",
    team: "Documentation Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436902/dgf1tlwxxyfmvqrxz6wm.jpg",
    linkedin_url: "https://www.linkedin.com/in/megh-gupta-95a97b228/",
    insta_url: "https://www.instagram.com/megh2409/",
  },
  
  // Event Team
  {
    Column2: "1/3/2024 23:58:35",
    name: "Pelapudi Vashishta ",
    position: "Head",
    team: "Event",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436899/knp9vwz83mjc77rah9hx.jpg",
    linkedin_url: "https://www.linkedin.com/in/pelapudi-vashishta-008541226?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    insta_url: "https://www.instagram.com/pelapudi_vashishta?igsh=MTRpbmIxMG1wMnpnaQ==",
  },
  {
    Column2: "1/4/2024 22:49:31",
    name: "Prakalp",
    position: "Co-Head",
    team: "Event management team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436954/lvdcmxampbcfrbsashzm.jpg",
    linkedin_url: "https://www.linkedin.com/in/prakalpthakur/",
    insta_url: "https://www.instagram.com/_.prakalp._?igsh=ODA1NTc5OTg5Nw==",
  },
  {
    Column2: "1/4/2024 18:48:07",
    name: "Mythili Balachandran",
    position: "Co-Head",
    team: "Event team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436893/x5evb4zpk7ootmtkhtlu.jpg",
    linkedin_url: "https://www.linkedin.com/in/mythili-balachandran-a7a341263/",
    insta_url: "https://www.instagram.com/myth.lili/",
  },
  {
    Column2: "1/4/2024 22:24:02",
    name: "Harsh Mishra",
    position: "Head",
    team: "Event Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436946/yzdvnbvuwzws75qh4vlg.jpg",
    linkedin_url: "www.linkedin.com/in/harsh-mishra-9b1399235",
    insta_url: "https://www.instagram.com/harshmishra3105/",
  },
  
  // Finance Team
  {
    Column2: "1/4/2024 19:49:16",
    name: "KARTHIK SHARNA",
    position: "Head",
    team: "FINANCE",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436912/ovqofbiibofgftvoln64.jpg",
    linkedin_url: "https://www.linkedin.com/in/madugula-karthik-sharma-2a389425a/",
    insta_url: "https://www.instagram.com/karthik_sharma._?igsh=MXc2eHo1MG83eXI0Mg==",
  },
  
  // Hospitality Team
  {
    Column2: "1/3/2024 23:59:52",
    name: "Bendi Bhargav",
    position: "Co-Head",
    team: "Hospitality Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436895/xgg6qmozw3ebgvxa5q3l.jpg",
    linkedin_url: "https://www.linkedin.com/in/bhargav-bendi-08a34a237?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    insta_url: "https://www.instagram.com/bhargav_bendi?igsh=dXRkemlvNnE1c2lq",
  },
  {
    Column2: "1/4/2024 15:53:23",
    name: "Pintu Kumar Meena ",
    position: "Head",
    team: "Hospitality ",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436908/ntmtqrjdnfvdph70kol1.jpg",
    linkedin_url: "https://www.linkedin.com/in/pintu-m-098005233",
    insta_url: "https://www.instagram.com/pintu_meena_2603?igsh=cmttZDRtazQ4Y3Q3",
  },
  {
    Column2: "1/4/2024 16:12:39",
    name: "Abhinav Pratham",
    position: "Co-Head",
    team: "Hospitality ",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436895/uad0y8hwlitr1h8ophk3.jpg",
    linkedin_url: "https://www.linkedin.com/in/abhinavpratham",
    insta_url: ".",
  },
  {
    Column2: "1/4/2024 16:45:09",
    name: "Vaishnavi Titare",
    position: "Co-Head",
    team: "Hospitality",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436903/hx4dcb3nqwp844hvzguv.jpg",
    linkedin_url: "https://www.linkedin.com/in/vaishnavi-titare-1312a5235",
    insta_url: "https://www.instagram.com/_vaishuu__._?utm_source=qr&igsh=ZDViMGNmM2Q%3D",
  },
  
  // Public Relations
  {
    Column2: "1/4/2024 16:11:19",
    name: "Akshat Laddha",
    position: "Co-Head",
    team: "Public Relation ",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436911/obnfbbezcxozfy7ecgvj.jpg",
    linkedin_url: "https://www.linkedin.com/in/akshat-laddha-a6078b227",
    insta_url: "https://www.instagram.com/akshat_laddha__/?igsh=ZDViMDNmZmQ%3D",
  },
  {
    Column2: "1/4/2024 17:00:38",
    name: "Arya Chetan Sahu",
    position: "Co-Head",
    team: "Public Relation Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436905/k7fbbgg7rvzqfau0rj3r.jpg",
    linkedin_url: "https://www.linkedin.com/in/arya-chetan-sahu-667923218",
    insta_url: "https://www.instagram.com/arya_chetan_sahu/",
  },
  {
    Column2: "1/4/2024 22:30:35",
    name: "Tanishqa Bhadoriya ",
    position: "Head",
    team: "Public Relation Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436952/wmspnksinorxtxqemebs.jpg",
    linkedin_url: "https://www.linkedin.com/in/tanishqa-bhadoriya-002317226?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    insta_url: "https://www.instagram.com/tanishqa_2305?igsh=ZDViMGNmZQ%3D%3D",
  },
  {
    Column2: "1/4/2024 22:54:14",
    name: "Puneet Singhal",
    position: "Co-Head",
    team: "Public Relations Team",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436956/ujs6czycgdy5ylfeizri.jpg",
    linkedin_url: "https://www.linkedin.com/in/puneet-singhal-2010a822b",
    insta_url: "https://www.instagram.com/puneet_singhal05?igsh=ZDc0MGQ3ZmQ%3D",
  },
  
  // Safety & Security
  {
    Column2: "1/3/2024 23:13:53",
    name: "Lakshya Garg",
    position: "Co-Head",
    team: "Safety & Security",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436892/hs4urqqpeibrk4vbwjvi.jpg",
    linkedin_url: "https://www.linkedin.com/in/lakshya-garg-903999227?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    insta_url: "https://www.instagram.com/15_lakshya?igsh=amxpb2cwcHZkcHE1&utm_source=qr",
  },
  {
    Column2: "1/4/2024 15:51:51",
    name: "Shaik Rumman Ahamed ",
    position: "Head",
    team: "Safety & Security",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436940/eip29zsbdfyrnzhupxup.jpg",
    linkedin_url: "https://www.linkedin.com/in/rumman-ahamed-2376a1225",
    insta_url: "https://www.instagram.com/rumman_ahamed?igsh=ZDViMDNmZmQ%3D",
  },
  
  // Sponsorship Team
  {
    Column2: "1/4/2024 15:45:14",
    name: "G SAI PRANEETH",
    position: "Head",
    team: "Sponsorship",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436932/ky0ztluz9ux1ff0ph0v1.jpg",
    linkedin_url: "https://www.linkedin.com/in/sai-praneeth-0b26b6242",
    insta_url: "https://www.instagram.com/sai_praneeth__0.1",
  },
  
  // Technical Team
  {
    Column2: "1/3/2024 23:13:23",
    name: "Aditya Dung",
    position: "Head",
    team: "Technical",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436912/ij8tmkjh77tyo8jlreow.jpg",
    linkedin_url: "https://www.linkedin.com/in/aditya-dung-8b2821234?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    insta_url: "https://www.instagram.com/aditya__dung/",
  },
  {
    Column2: "1/4/2024 15:33:28",
    name: "Krishna Agrawal ",
    position: "Co-Head",
    team: "Technical",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436891/sxftjowhxm1ecyoyz0lj.jpg",
    linkedin_url: "https://www.linkedin.com/in/krishna-agrawal-780b18223",
    insta_url: "https://www.instagram.com/krishna_agrawal17",
  },
  {
    Column2: "1/4/2024 16:36:28",
    name: "Soumya Ranjan  Rout ",
    position: "Co-Head",
    team: "Technical",
    image: "http://res.cloudinary.com/dthfm5ips/image/upload/v1717436942/lrrv0t5tfo0ed2m5f1m7.jpg",
    linkedin_url: "https://www.linkedin.com/in/soumya-ranjan-rout-9b9635235",
    insta_url: "https://www.instagram.com/_soumya_ranjan_rout_",
  },
];
